# Generated by Django 6.0.7 on 2026-07-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('coco_id', models.CharField(db_index=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('fancy_name', models.CharField(blank=True, max_length=300)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='CurrentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('deviation', models.FloatField()),
                ('career_games', models.IntegerField()),
                ('last_played', models.DateField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_rating', to='ratings.player')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('old_deviation', models.FloatField()),
                ('new_deviation', models.FloatField()),
                ('games', models.IntegerField()),
                ('wins', models.FloatField()),
                ('losses', models.FloatField()),
                ('spread', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ratings.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ratings.tournament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'tournament'), name='unique_player_tournament')],
            },
        ),
    ]
