# Generated by Django 6.0.7 on 2026-07-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_trigram_extension'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrating',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computed_rating', to='players.player'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_results', to='players.player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
