# Generated by Django 6.0.7 on 2026-08-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_currentrating_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['date', 'order', 'filename']},
        ),
        migrations.AddField(
            model_name='tournament',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
