# Generated by Django 6.0.7 on 2026-07-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_trigram_extension'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_player_date',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
