# Generated by Django 6.0.7 on 2026-08-19 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_pad_player_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('payout_preference', models.CharField(blank=True, help_text='How this player prefers to be paid out (free text).', max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='players.player')),
            ],
            options={
                'verbose_name': 'player details',
                'verbose_name_plural': 'player details',
            },
        ),
    ]
